spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

---
# 로컬 환경
spring.config.activate.on-profile: local
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: /* input value */
    username: /* input value */
    password: /* input value */

  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

---
# 테스트 환경
spring.config.activate.on-profile: test
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: /* input value */
    username: /* input value */
    password: /* input value */

  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

